name: "Solicitud de Prestaciones"
description: "Solicita un servicio o soporte t茅cnico del SIO-ICM."
title: "[Solicitud] Breve descripci贸n del servicio requerido"
labels:
  - "solicitud"
  - "pendiente revisi贸n"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ##  Solicitud de Prestaci贸n de Servicios del SIO
        Por favor, completa el siguiente formulario para solicitar un servicio.

  - type: dropdown
    id: pertenece_csic
    attributes:
      label: "驴Perteneces al CSIC?"
      options:
        - "S铆"
        - "No"

  - type: input
    id: nombre
    attributes:
      label: "Nombre y apellidos"
      placeholder: "Ejemplo: Juan P茅rez"

  - type: input
    id: telefono
    attributes:
      label: "Tel茅fono"
      placeholder: "Ejemplo: +34 600 123 456"

  - type: input
    id: email
    attributes:
      label: "Email"
      placeholder: "ejemplo@correo.com"

  - type: input
    id: direccion
    attributes:
      label: "Direcci贸n"
      placeholder: "Calle, n煤mero, CP, Ciudad"

  - type: input
    id: centro
    attributes:
      label: "Centro"
      placeholder: "Ejemplo: ICM-CSIC"

  - type: input
    id: departamento
    attributes:
      label: "Departamento/Grupo de investigaci贸n"
      placeholder: "Ejemplo: Oceanograf铆a F铆sica"

  - type: input
    id: nombre_proyecto
    attributes:
      label: "Nombre del proyecto/acr贸nimo"
      placeholder: "Ejemplo: PROYECTO-MAR"

  - type: input
    id: referencia_proyecto
    attributes:
      label: "Referencia del proyecto"
      placeholder: "Ejemplo: 2024-ICM-001"

  - type: input
    id: responsable_proyecto
    attributes:
      label: "Responsable del proyecto"
      placeholder: "Ejemplo: Dra. Mar铆a L贸pez"

  - type: input
    id: email_responsable
    attributes:
      label: "Email del Responsable del proyecto"
      placeholder: "ejemplo@institucion.com"

  - type: dropdown
    id: tipo_prestacion
    attributes:
      label: "Prestaci贸n requerida"
      options:
        - "Uso de embarcaciones con patr贸n para campa帽as y mediciones"
        - "Uso de tanques de experimentaci贸n en 谩reas controladas"
        - "Asesoramiento en campa帽as oceanogr谩ficas"
        - "Caracterizaci贸n de agua marina con perfilador vertical"
        - "Despliegue y mantenimiento de instrumentaci贸n oceanogr谩fica"
        - "Dise帽o, desarrollo e instalaci贸n de sensores, sistemas de observaci贸n y fondeos"
        - "Ejecuci贸n de campa帽as oceanogr谩ficas"
        - "An谩lisis de salinidad del agua"
        - "Verificaci贸n de instrumentaci贸n"
        - "Reparaci贸n de instrumentaci贸n oceanogr谩fica"

  - type: textarea
    id: descripcion
    attributes:
      label: "Descripci贸n detallada de la necesidad"
      description: "Describe qu茅 necesitas y cualquier informaci贸n relevante."
      placeholder: "Ejemplo: Necesitamos desplegar un perfilador de CTD en la Bah铆a de Palma para una campa帽a de 2 semanas."
      render: markdown

  - type: input
    id: fecha_solicitud
    attributes:
      label: "Fecha estimada del servicio"
      placeholder: "Ejemplo: 15/06/2024"

  - type: checkboxes
    id: confirmacion
    attributes:
      label: "Confirmaci贸n"
      options:
        - label: "Confirmo que he revisado la documentaci贸n disponible antes de enviar esta solicitud."
