name: "Solicitud de Prestaciones"
description: "Solicita un servicio o soporte t茅cnico del SIO-ICM."
title: "[Solicitud] Breve descripci贸n del servicio requerido"
labels:
  - "solicitud"
  - "pendiente revisi贸n"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ##  Solicitud de Prestaci贸n de Servicios del SIO
        Por favor, completa el siguiente formulario para solicitar un servicio.

  - type: dropdown
    id: tipo_prestacion
    attributes:
      label: "Prestaci贸n requerida"
      options:
        - "Uso de embarcaciones con patr贸n para campa帽as y mediciones"
        - "Uso de tanques de experimentaci贸n en 谩reas controladas"
        - "Asesoramiento en campa帽as oceanogr谩ficas"
        - "Caracterizaci贸n de agua marina con perfilador vertical"
        - "Despliegue y mantenimiento de instrumentaci贸n oceanogr谩fica"
        - "Dise帽o, desarrollo e instalaci贸n de sensores, sistemas de observaci贸n y fondeos"
        - "Ejecuci贸n de campa帽as oceanogr谩ficas"
        - "An谩lisis de salinidad del agua"
        - "Verificaci贸n de instrumentaci贸n"
        - "Reparaci贸n de instrumentaci贸n oceanogr谩fica"

  - type: textarea
    id: descripcion
    attributes:
      label: "Descripci贸n detallada de la necesidad"
      description: "Describe qu茅 necesitas y cualquier informaci贸n relevante."
      placeholder: "Ejemplo: Necesitamos desplegar un perfilador de CTD en la Bah铆a de Palma para una campa帽a de 2 semanas."
      render: markdown

  - type: input
    id: fecha_inicio
    attributes:
      label: "Fecha estimada de inicio de la prestaci贸n"
      placeholder: "Ejemplo: 15/06/2024"

  - type: input
    id: fecha_fin
    attributes:
      label: "Fecha estimada de finalizaci贸n de la prestaci贸n"
      description: "Si no es un rango temporal, solo especifica la fecha de finalizaci贸n."
      placeholder: "Ejemplo: 30/06/2024"

  - type: markdown
    attributes:
      value: |
        ---
        ##  Informaci贸n del Solicitante
        A continuaci贸n, proporciona tus datos personales y del proyecto asociado a la solicitud.

  - type: input
    id: nombre
    attributes:
      label: "Nombre y apellidos"
      placeholder: "Ejemplo: Juan P茅rez"

  - type: input
    id: email
    attributes:
      label: "Email"
      placeholder: "ejemplo@correo.com"

  - type: dropdown
    id: pertenece_csic
    attributes:
      label: "驴Perteneces al CSIC?"
      options:
        - "S铆"
        - "No"

  - type: input
    id: centro
    attributes:
      label: "Centro (solo si perteneces al CSIC)"
      placeholder: "Ejemplo: ICM-CSIC"

  - type: input
    id: departamento
    attributes:
      label: "Departamento/Grupo de investigaci贸n (solo si perteneces al CSIC)"
      placeholder: "Ejemplo: Oceanograf铆a F铆sica"

  - type: input
    id: empresa
    attributes:
      label: "Nombre de la empresa (solo si NO perteneces al CSIC)"
      placeholder: "Ejemplo: OceanTech SL"

  - type: input
    id: direccion
    attributes:
      label: "Direcci贸n (solo si NO perteneces al CSIC)"
      placeholder: "Calle, n煤mero, CP, Ciudad"

  - type: input
    id: telefono
    attributes:
      label: "N煤mero de tel茅fono (solo si NO perteneces al CSIC)"
      placeholder: "Ejemplo: +34 600 123 456"

  - type: input
    id: nombre_proyecto
    attributes:
      label: "Nombre del proyecto/acr贸nimo"
      placeholder: "Ejemplo: PROYECTO-MAR"

  - type: input
    id: responsable_proyecto
    attributes:
      label: "Responsable del proyecto"
      placeholder: "Ejemplo: Dra. Mar铆a L贸pez"

  - type: input
    id: email_responsable
    attributes:
      label: "Email del Responsable del proyecto"
      placeholder: "ejemplo@institucion.com"
